# data config
dataset: pubmed
split: train
max_token_length: 1024

# model config
step: 110000
model: allenai/OLMo-7B-hf

# trainer config
batch_size: 16
accumulate_grad_batches: 16
max_epochs: 1
lr: 1e-4
scheduler: constant
gradient_clip_val: 1.0
save_strategy: epoch
save_only_model: True
report_to: wandb 

# global config
mode: train
save_dir: checkpoints/finetuned_1ep/110000_1ep_bs1024_1e4_constant
debug_data: False
seed: 42