# data config
dataset: pubmed
split: train
max_token_length: 1024

# model config
step: 502000
model: allenai/OLMo-7B-hf

# trainer config
batch_size: 16
accumulate_grad_batches: 2
max_epochs: 3
lr: 7e-5
warmup_ratio: 0.03
scheduler: cosine
gradient_clip_val: 1.0
save_strategy: "no"
save_only_model: True
report_to: wandb 

# global config
mode: train
save_dir: checkpoints/finetuned_variants/7e5_3ep/502000_bs128_7e5_3ep_cosine
debug_data: False
seed: 42